- name: Instalar pacotes NTP
  apt:
    name: ntp
    state: present
    update_cache: yes

- name: Configurar arquivo ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart NTP

- name: Garantir que o NTP está rodando
  service:
    name: ntp
    state: started
    enabled: yes

- name: Desativar root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH

- name: Atualizar pacotes críticos
  apt:
    upgrade: dist
    update_cache: yes

handlers:
  - name: Restart NTP
    service:
      name: ntp
      state: restarted
  - name: Restart SSH
    service:
      name: ssh
      state: restarted

