- name: Instalar Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configurar página inicial
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644

- name: Garantir que o Nginx está rodando
  service:
    name: nginx
    state: started
    enabled: yes

